const HIRAGANA = [
  { char: "あ", romaji: "a", group: "gojuon" }, { char: "い", romaji: "i", group: "gojuon" },
  { char: "う", romaji: "u", group: "gojuon" }, { char: "え", romaji: "e", group: "gojuon" },
  { char: "お", romaji: "o", group: "gojuon" },
  { char: "か", romaji: "ka", group: "gojuon" }, { char: "き", romaji: "ki", group: "gojuon" },
  { char: "く", romaji: "ku", group: "gojuon" }, { char: "け", romaji: "ke", group: "gojuon" },
  { char: "こ", romaji: "ko", group: "gojuon" },
  { char: "さ", romaji: "sa", group: "gojuon" }, { char: "し", romaji: "shi", group: "gojuon" },
  { char: "す", romaji: "su", group: "gojuon" }, { char: "せ", romaji: "se", group: "gojuon" },
  { char: "そ", romaji: "so", group: "gojuon" },
  { char: "た", romaji: "ta", group: "gojuon" }, { char: "ち", romaji: "chi", group: "gojuon" },
  { char: "つ", romaji: "tsu", group: "gojuon" }, { char: "て", romaji: "te", group: "gojuon" },
  { char: "と", romaji: "to", group: "gojuon" },
  { char: "な", romaji: "na", group: "gojuon" }, { char: "に", romaji: "ni", group: "gojuon" },
  { char: "ぬ", romaji: "nu", group: "gojuon" }, { char: "ね", romaji: "ne", group: "gojuon" },
  { char: "の", romaji: "no", group: "gojuon" },
  { char: "は", romaji: "ha", group: "gojuon" }, { char: "ひ", romaji: "hi", group: "gojuon" },
  { char: "ふ", romaji: "fu", group: "gojuon" }, { char: "へ", romaji: "he", group: "gojuon" },
  { char: "ほ", romaji: "ho", group: "gojuon" },
  { char: "ま", romaji: "ma", group: "gojuon" }, { char: "み", romaji: "mi", group: "gojuon" },
  { char: "む", romaji: "mu", group: "gojuon" }, { char: "め", romaji: "me", group: "gojuon" },
  { char: "も", romaji: "mo", group: "gojuon" },
  { char: "や", romaji: "ya", group: "gojuon" }, { char: "ゆ", romaji: "yu", group: "gojuon" },
  { char: "よ", romaji: "yo", group: "gojuon" },
  { char: "ら", romaji: "ra", group: "gojuon" }, { char: "り", romaji: "ri", group: "gojuon" },
  { char: "る", romaji: "ru", group: "gojuon" }, { char: "れ", romaji: "re", group: "gojuon" },
  { char: "ろ", romaji: "ro", group: "gojuon" },
  { char: "わ", romaji: "wa", group: "gojuon" }, { char: "を", romaji: "wo", group: "gojuon" },
  { char: "ん", romaji: "n", group: "gojuon" },
  { char: "が", romaji: "ga", group: "dakuon" }, { char: "ぎ", romaji: "gi", group: "dakuon" },
  { char: "ぐ", romaji: "gu", group: "dakuon" }, { char: "げ", romaji: "ge", group: "dakuon" },
  { char: "ご", romaji: "go", group: "dakuon" },
  { char: "ざ", romaji: "za", group: "dakuon" }, { char: "じ", romaji: "ji", group: "dakuon" },
  { char: "ず", romaji: "zu", group: "dakuon" }, { char: "ぜ", romaji: "ze", group: "dakuon" },
  { char: "ぞ", romaji: "zo", group: "dakuon" },
  { char: "だ", romaji: "da", group: "dakuon" }, { char: "ぢ", romaji: "ji", group: "dakuon" },
  { char: "づ", romaji: "zu", group: "dakuon" }, { char: "で", romaji: "de", group: "dakuon" },
  { char: "ど", romaji: "do", group: "dakuon" },
  { char: "ば", romaji: "ba", group: "dakuon" }, { char: "び", romaji: "bi", group: "dakuon" },
  { char: "ぶ", romaji: "bu", group: "dakuon" }, { char: "べ", romaji: "be", group: "dakuon" },
  { char: "ぼ", romaji: "bo", group: "dakuon" },
  { char: "ぱ", romaji: "pa", group: "handakuon" }, { char: "ぴ", romaji: "pi", group: "handakuon" },
  { char: "ぷ", romaji: "pu", group: "handakuon" }, { char: "ぺ", romaji: "pe", group: "handakuon" },
  { char: "ぽ", romaji: "po", group: "handakuon" },
  { char: "きゃ", romaji: "kya", group: "yoon" }, { char: "きゅ", romaji: "kyu", group: "yoon" }, { char: "きょ", romaji: "kyo", group: "yoon" },
  { char: "しゃ", romaji: "sha", group: "yoon" }, { char: "しゅ", romaji: "shu", group: "yoon" }, { char: "しょ", romaji: "sho", group: "yoon" },
  { char: "ちゃ", romaji: "cha", group: "yoon" }, { char: "ちゅ", romaji: "chu", group: "yoon" }, { char: "ちょ", romaji: "cho", group: "yoon" },
  { char: "にゃ", romaji: "nya", group: "yoon" }, { char: "にゅ", romaji: "nyu", group: "yoon" }, { char: "にょ", romaji: "nyo", group: "yoon" },
  { char: "ひゃ", romaji: "hya", group: "yoon" }, { char: "ひゅ", romaji: "hyu", group: "yoon" }, { char: "ひょ", romaji: "hyo", group: "yoon" },
  { char: "みゃ", romaji: "mya", group: "yoon" }, { char: "みゅ", romaji: "myu", group: "yoon" }, { char: "みょ", romaji: "myo", group: "yoon" },
  { char: "りゃ", romaji: "rya", group: "yoon" }, { char: "りゅ", romaji: "ryu", group: "yoon" }, { char: "りょ", romaji: "ryo", group: "yoon" },
  { char: "ぎゃ", romaji: "gya", group: "yoon" }, { char: "ぎゅ", romaji: "gyu", group: "yoon" }, { char: "ぎょ", romaji: "gyo", group: "yoon" },
  { char: "じゃ", romaji: "ja", group: "yoon" }, { char: "じゅ", romaji: "ju", group: "yoon" }, { char: "じょ", romaji: "jo", group: "yoon" },
  { char: "びゃ", romaji: "bya", group: "yoon" }, { char: "びゅ", romaji: "byu", group: "yoon" }, { char: "びょ", romaji: "byo", group: "yoon" },
  { char: "ぴゃ", romaji: "pya", group: "yoon" }, { char: "ぴゅ", romaji: "pyu", group: "yoon" }, { char: "ぴょ", romaji: "pyo", group: "yoon" },
];

const KATAKANA = [
  { char: "ア", romaji: "a", group: "gojuon" }, { char: "イ", romaji: "i", group: "gojuon" },
  { char: "ウ", romaji: "u", group: "gojuon" }, { char: "エ", romaji: "e", group: "gojuon" },
  { char: "オ", romaji: "o", group: "gojuon" },
  { char: "カ", romaji: "ka", group: "gojuon" }, { char: "キ", romaji: "ki", group: "gojuon" },
  { char: "ク", romaji: "ku", group: "gojuon" }, { char: "ケ", romaji: "ke", group: "gojuon" },
  { char: "コ", romaji: "ko", group: "gojuon" },
  { char: "サ", romaji: "sa", group: "gojuon" }, { char: "シ", romaji: "shi", group: "gojuon" },
  { char: "ス", romaji: "su", group: "gojuon" }, { char: "セ", romaji: "se", group: "gojuon" },
  { char: "ソ", romaji: "so", group: "gojuon" },
  { char: "タ", romaji: "ta", group: "gojuon" }, { char: "チ", romaji: "chi", group: "gojuon" },
  { char: "ツ", romaji: "tsu", group: "gojuon" }, { char: "テ", romaji: "te", group: "gojuon" },
  { char: "ト", romaji: "to", group: "gojuon" },
  { char: "ナ", romaji: "na", group: "gojuon" }, { char: "ニ", romaji: "ni", group: "gojuon" },
  { char: "ヌ", romaji: "nu", group: "gojuon" }, { char: "ネ", romaji: "ne", group: "gojuon" },
  { char: "ノ", romaji: "no", group: "gojuon" },
  { char: "ハ", romaji: "ha", group: "gojuon" }, { char: "ヒ", romaji: "hi", group: "gojuon" },
  { char: "フ", romaji: "fu", group: "gojuon" }, { char: "ヘ", romaji: "he", group: "gojuon" },
  { char: "ホ", romaji: "ho", group: "gojuon" },
  { char: "マ", romaji: "ma", group: "gojuon" }, { char: "ミ", romaji: "mi", group: "gojuon" },
  { char: "ム", romaji: "mu", group: "gojuon" }, { char: "メ", romaji: "me", group: "gojuon" },
  { char: "モ", romaji: "mo", group: "gojuon" },
  { char: "ヤ", romaji: "ya", group: "gojuon" }, { char: "ユ", romaji: "yu", group: "gojuon" },
  { char: "ヨ", romaji: "yo", group: "gojuon" },
  { char: "ラ", romaji: "ra", group: "gojuon" }, { char: "リ", romaji: "ri", group: "gojuon" },
  { char: "ル", romaji: "ru", group: "gojuon" }, { char: "レ", romaji: "re", group: "gojuon" },
  { char: "ロ", romaji: "ro", group: "gojuon" },
  { char: "ワ", romaji: "wa", group: "gojuon" }, { char: "ヲ", romaji: "wo", group: "gojuon" },
  { char: "ン", romaji: "n", group: "gojuon" },
  { char: "ガ", romaji: "ga", group: "dakuon" }, { char: "ギ", romaji: "gi", group: "dakuon" },
  { char: "グ", romaji: "gu", group: "dakuon" }, { char: "ゲ", romaji: "ge", group: "dakuon" },
  { char: "ゴ", romaji: "go", group: "dakuon" },
  { char: "ザ", romaji: "za", group: "dakuon" }, { char: "ジ", romaji: "ji", group: "dakuon" },
  { char: "ズ", romaji: "zu", group: "dakuon" }, { char: "ゼ", romaji: "ze", group: "dakuon" },
  { char: "ゾ", romaji: "zo", group: "dakuon" },
  { char: "ダ", romaji: "da", group: "dakuon" }, { char: "ヂ", romaji: "ji", group: "dakuon" },
  { char: "ヅ", romaji: "zu", group: "dakuon" }, { char: "デ", romaji: "de", group: "dakuon" },
  { char: "ド", romaji: "do", group: "dakuon" },
  { char: "バ", romaji: "ba", group: "dakuon" }, { char: "ビ", romaji: "bi", group: "dakuon" },
  { char: "ブ", romaji: "bu", group: "dakuon" }, { char: "ベ", romaji: "be", group: "dakuon" },
  { char: "ボ", romaji: "bo", group: "dakuon" },
  { char: "パ", romaji: "pa", group: "handakuon" }, { char: "ピ", romaji: "pi", group: "handakuon" },
  { char: "プ", romaji: "pu", group: "handakuon" }, { char: "ペ", romaji: "pe", group: "handakuon" },
  { char: "ポ", romaji: "po", group: "handakuon" },
  { char: "キャ", romaji: "kya", group: "yoon" }, { char: "キュ", romaji: "kyu", group: "yoon" }, { char: "キョ", romaji: "kyo", group: "yoon" },
  { char: "シャ", romaji: "sha", group: "yoon" }, { char: "シュ", romaji: "shu", group: "yoon" }, { char: "ショ", romaji: "sho", group: "yoon" },
  { char: "チャ", romaji: "cha", group: "yoon" }, { char: "チュ", romaji: "chu", group: "yoon" }, { char: "チョ", romaji: "cho", group: "yoon" },
  { char: "ニャ", romaji: "nya", group: "yoon" }, { char: "ニュ", romaji: "nyu", group: "yoon" }, { char: "ニョ", romaji: "nyo", group: "yoon" },
  { char: "ヒャ", romaji: "hya", group: "yoon" }, { char: "ヒュ", romaji: "hyu", group: "yoon" }, { char: "ヒョ", romaji: "hyo", group: "yoon" },
  { char: "ミャ", romaji: "mya", group: "yoon" }, { char: "ミュ", romaji: "myu", group: "yoon" }, { char: "ミョ", romaji: "myo", group: "yoon" },
  { char: "リャ", romaji: "rya", group: "yoon" }, { char: "リュ", romaji: "ryu", group: "yoon" }, { char: "リョ", romaji: "ryo", group: "yoon" },
  { char: "ギャ", romaji: "gya", group: "yoon" }, { char: "ギュ", romaji: "gyu", group: "yoon" }, { char: "ギョ", romaji: "gyo", group: "yoon" },
  { char: "ジャ", romaji: "ja", group: "yoon" }, { char: "ジュ", romaji: "ju", group: "yoon" }, { char: "ジョ", romaji: "jo", group: "yoon" },
  { char: "ビャ", romaji: "bya", group: "yoon" }, { char: "ビュ", romaji: "byu", group: "yoon" }, { char: "ビョ", romaji: "byo", group: "yoon" },
  { char: "ピャ", romaji: "pya", group: "yoon" }, { char: "ピュ", romaji: "pyu", group: "yoon" }, { char: "ピョ", romaji: "pyo", group: "yoon" },
];

const KANJI = [
  { char: "日", romaji: "hi", meaning: { id: "matahari / hari", en: "sun / day" }, group: "dasar" },
  { char: "月", romaji: "tsuki", meaning: { id: "bulan", en: "moon" }, group: "dasar" },
  { char: "火", romaji: "hi", meaning: { id: "api", en: "fire" }, group: "dasar" },
  { char: "水", romaji: "mizu", meaning: { id: "air", en: "water" }, group: "dasar" },
  { char: "木", romaji: "ki", meaning: { id: "pohon", en: "tree" }, group: "dasar" },
  { char: "金", romaji: "kin", meaning: { id: "emas / uang", en: "gold / money" }, group: "dasar" },
  { char: "土", romaji: "tsuchi", meaning: { id: "tanah", en: "earth / soil" }, group: "dasar" },
  { char: "人", romaji: "hito", meaning: { id: "orang", en: "person" }, group: "dasar" },
  { char: "一", romaji: "ichi", meaning: { id: "satu", en: "one" }, group: "angka" },
  { char: "二", romaji: "ni", meaning: { id: "dua", en: "two" }, group: "angka" },
  { char: "三", romaji: "san", meaning: { id: "tiga", en: "three" }, group: "angka" },
  { char: "四", romaji: "yon", meaning: { id: "empat", en: "four" }, group: "angka" },
  { char: "五", romaji: "go", meaning: { id: "lima", en: "five" }, group: "angka" },
  { char: "六", romaji: "roku", meaning: { id: "enam", en: "six" }, group: "angka" },
  { char: "七", romaji: "nana", meaning: { id: "tujuh", en: "seven" }, group: "angka" },
  { char: "八", romaji: "hachi", meaning: { id: "delapan", en: "eight" }, group: "angka" },
  { char: "九", romaji: "kyuu", meaning: { id: "sembilan", en: "nine" }, group: "angka" },
  { char: "十", romaji: "juu", meaning: { id: "sepuluh", en: "ten" }, group: "angka" },
  { char: "大", romaji: "ookii", meaning: { id: "besar", en: "big" }, group: "sifat" },
  { char: "小", romaji: "chiisai", meaning: { id: "kecil", en: "small" }, group: "sifat" },
  { char: "中", romaji: "naka", meaning: { id: "tengah / dalam", en: "middle / inside" }, group: "sifat" },
  { char: "上", romaji: "ue", meaning: { id: "atas", en: "up / above" }, group: "sifat" },
  { char: "下", romaji: "shita", meaning: { id: "bawah", en: "down / below" }, group: "sifat" },
  { char: "本", romaji: "hon", meaning: { id: "buku / asal", en: "book / origin" }, group: "benda" },
  { char: "山", romaji: "yama", meaning: { id: "gunung", en: "mountain" }, group: "alam" },
  { char: "川", romaji: "kawa", meaning: { id: "sungai", en: "river" }, group: "alam" },
  { char: "天", romaji: "ten", meaning: { id: "langit", en: "sky" }, group: "alam" },
  { char: "気", romaji: "ki", meaning: { id: "udara / semangat", en: "air / spirit" }, group: "alam" },
  { char: "子", romaji: "ko", meaning: { id: "anak", en: "child" }, group: "orang" },
  { char: "女", romaji: "onna", meaning: { id: "perempuan", en: "woman" }, group: "orang" },
  { char: "男", romaji: "otoko", meaning: { id: "laki-laki", en: "man" }, group: "orang" },
  { char: "学", romaji: "gaku", meaning: { id: "belajar / ilmu", en: "study / learning" }, group: "sekolah" },
  { char: "校", romaji: "kou", meaning: { id: "sekolah", en: "school" }, group: "sekolah" },
  { char: "語", romaji: "go", meaning: { id: "bahasa", en: "language" }, group: "sekolah" },
  { char: "名", romaji: "na", meaning: { id: "nama", en: "name" }, group: "orang" },
  { char: "父", romaji: "chichi", meaning: { id: "ayah", en: "father" }, group: "keluarga" },
  { char: "母", romaji: "haha", meaning: { id: "ibu", en: "mother" }, group: "keluarga" },
  { char: "友", romaji: "tomo", meaning: { id: "teman", en: "friend" }, group: "orang" },
  { char: "今", romaji: "ima", meaning: { id: "sekarang", en: "now" }, group: "waktu" },
  { char: "何", romaji: "nani", meaning: { id: "apa", en: "what" }, group: "tanya" },
];

const KANA_GROUPS = [
  { key: "gojuon", label: { id: "Gojuon (Huruf Dasar)", en: "Gojuon (Basic Characters)" }, desc: { id: "46 huruf dasar — pondasi dari semua bacaan.", en: "46 basic characters — the foundation of all readings." } },
  { key: "dakuon", label: { id: "Dakuon (Tanda Titik Dua ゛)", en: "Dakuon (Two-Dot Mark ゛)" }, desc: { id: "Huruf dasar yang diberi tanda ゛ sehingga bunyinya berubah, misalnya か (ka) jadi が (ga).", en: "Basic characters marked with ゛ that change their sound, e.g. か (ka) becomes が (ga)." } },
  { key: "handakuon", label: { id: "Handakuon (Tanda Bulatan ゜)", en: "Handakuon (Circle Mark ゜)" }, desc: { id: "Khusus baris は/ハ yang diberi tanda ゜ sehingga berbunyi p, misalnya は (ha) jadi ぱ (pa).", en: "Only the は/ハ row marked with ゜ to make a p sound, e.g. は (ha) becomes ぱ (pa)." } },
  { key: "yoon", label: { id: "Yōon (Huruf Gabungan)", en: "Yōon (Combined Characters)" }, desc: { id: "Huruf i-baris yang digabung dengan や/ゆ/よ kecil untuk membuat satu bunyi baru, misalnya き + ゃ = きゃ (kya).", en: "i-row characters combined with a small や/ゆ/よ to form one new sound, e.g. き + ゃ = きゃ (kya)." } },
];

const KANJI_GROUPS = [
  { key: "dasar", label: { id: "Kanji Alam & Unsur", en: "Elements Kanji" }, desc: { id: "Kanji dasar seperti hari, bulan, api, dan air.", en: "Basic kanji like day, moon, fire, and water." } },
  { key: "angka", label: { id: "Kanji Angka", en: "Number Kanji" }, desc: { id: "Angka 1 sampai 10 dalam kanji.", en: "Numbers 1 to 10 in kanji." } },
  { key: "sifat", label: { id: "Kanji Sifat & Arah", en: "Descriptive & Direction Kanji" }, desc: { id: "Besar, kecil, atas, bawah, dan sejenisnya.", en: "Big, small, up, down, and similar." } },
  { key: "orang", label: { id: "Kanji Orang & Keluarga", en: "People & Family Kanji" }, desc: { id: "Anak, perempuan, laki-laki, nama, teman.", en: "Child, woman, man, name, friend." } },
  { key: "sekolah", label: { id: "Kanji Sekolah", en: "School Kanji" }, desc: { id: "Belajar, sekolah, bahasa.", en: "Study, school, language." } },
  { key: "alam", label: { id: "Kanji Alam", en: "Nature Kanji" }, desc: { id: "Gunung, sungai, langit, udara.", en: "Mountain, river, sky, air." } },
  { key: "keluarga", label: { id: "Kanji Keluarga", en: "Family Kanji" }, desc: { id: "Ayah dan ibu.", en: "Father and mother." } },
  { key: "waktu", label: { id: "Kanji Waktu & Tanya", en: "Time & Question Kanji" }, desc: { id: "Sekarang dan apa.", en: "Now and what." } },
];

const POINTS_PER_STAGE = 100;
const POINT_CORRECT_BASE = 10;
const POINT_HINT_PENALTY = 3;
const POINT_MIN_CORRECT = 3;
const POINT_WRONG = 0;
const DAILY_BONUS_POINTS = 5;

const I18N = {
  id: {
    switchLangLabel: "Bahasa: Indonesia",
    sidebarMenuTitle: "Menu",
    navHomeLabel: "Home",
    resetProgressLabel: "Reset Progress",
    resetConfirm: "Reset semua progres stage dan poin ke awal? Tindakan ini tidak bisa dibatalkan.",
    stageBadgeLabel: "Stage",
    stageBadgeSoal: "Soal",
    landingTitlePre: "Belajar",
    landingTitlePost: "Bahasa Jepang, Selangkah Demi Selangkah",
    landingSub: "Kenali Hiragana, Katakana, Kanji, dan Romaji lewat latihan singkat bergaya kuis. Santai, bisa diulang, dan progresmu tersimpan otomatis.",
    btnStartLearning: "Mulai Belajar",
    selectLangEyebrow: "Langkah 1",
    selectLangTitle: "Mau belajar tulisan yang mana?",
    selectLangSub: "Pilih salah satu untuk mulai berlatih.",
    descHiragana: "Huruf dasar untuk kata asli Jepang.",
    descKatakana: "Untuk kata serapan & nama asing.",
    descKanji: "Aksara makna dari Tiongkok kuno.",
    descRomaji: "Cara menulis bunyi Jepang pakai huruf latin.",
    stagePillPrefix: "Stage",
    backLinkHomeLabel: "Ganti tulisan",
    modeSelectEyebrow: "Langkah 2",
    modeSelectSub: "Pelajari dulu, atau langsung uji kemampuanmu?",
    basicTitle: "Pelajari Dulu",
    basicDesc: "Tutorial singkat per kelompok huruf sebelum latihan.",
    directTestTitle: "Langsung Tes",
    directTestDesc: "Lewati tutorial, langsung kerjakan soal acak.",
    stagePickerLabel: "Atau pilih stage tertentu:",
    stagePickerPointsPrefix: "poin",
    stageChipDone: "Ulang",
    stageChipCurrent: "Lanjut",
    stageChipLocked: "Terkunci",
    backLinkModeLabel: "Kembali",
    tutorialNextDefault: "Lanjut →",
    tutorialNextLast: "Mulai Tes →",
    kickerTypeA: "Tulis bacaan latinnya",
    kickerTypeAKanji: "Tulis cara bacanya (romaji)",
    kickerTypeB: "Pilih tulisan yang tepat",
    kickerTypeBKanji: "Pilih kanji yang tepat",
    meaningPrefix: "Arti:",
    inputPlaceholder: "ketik romaji...",
    btnCheckAnswer: "Periksa",
    btnNext: "Lanjut →",
    btnSeeResult: "Lihat Hasil",
    feedbackCorrect: "Benar!",
    feedbackWrong: "Kurang tepat, jangan menyerah!",
    answerPrefix: "Jawaban:",
    hintTitle: "Pakai hint",
    stageCompleteTitle: "Stage {n} Selesai!",
    scoreLineLabel: "Jawaban benar:",
    lockNoteLocked: "Kumpulkan {need} poin lagi di kategori ini untuk membuka Stage {n}.",
    btnRetryStage: "Coba Lagi",
    btnGoHome: "Home",
    btnNextStage: "Lanjut Stage →",
    autoSaveNote: "Progresmu otomatis tersimpan di browser ini.",
    dailyBonusToast: "🔥 Bonus harian +{pts} poin! Streak {streak} hari",
    antiCopyToast: "Fitur salin/inspect dinonaktifkan di halaman ini.",
  },
  en: {
    switchLangLabel: "Language: English",
    sidebarMenuTitle: "Menu",
    navHomeLabel: "Home",
    resetProgressLabel: "Reset Progress",
    resetConfirm: "Reset all stage progress and points to the start? This cannot be undone.",
    stageBadgeLabel: "Stage",
    stageBadgeSoal: "Question",
    landingTitlePre: "Learn",
    landingTitlePost: "Japanese, One Step at a Time",
    landingSub: "Get to know Hiragana, Katakana, Kanji, and Romaji through short quiz-style practice. Relaxed, repeatable, and your progress saves automatically.",
    btnStartLearning: "Start Learning",
    selectLangEyebrow: "Step 1",
    selectLangTitle: "Which script do you want to learn?",
    selectLangSub: "Pick one to start practicing.",
    descHiragana: "The basic script for native Japanese words.",
    descKatakana: "Used for loanwords & foreign names.",
    descKanji: "Meaning-based characters from ancient China.",
    descRomaji: "How Japanese sounds are written in Latin letters.",
    stagePillPrefix: "Stage",
    backLinkHomeLabel: "Change script",
    modeSelectEyebrow: "Step 2",
    modeSelectSub: "Learn the basics first, or jump straight into testing yourself?",
    basicTitle: "Learn First",
    basicDesc: "A short tutorial per character group before practice.",
    directTestTitle: "Test Directly",
    directTestDesc: "Skip the tutorial, jump straight into random questions.",
    stagePickerLabel: "Or pick a specific stage:",
    stagePickerPointsPrefix: "points",
    stageChipDone: "Redo",
    stageChipCurrent: "Continue",
    stageChipLocked: "Locked",
    backLinkModeLabel: "Back",
    tutorialNextDefault: "Next →",
    tutorialNextLast: "Start Test →",
    kickerTypeA: "Type the romaji reading",
    kickerTypeAKanji: "Type the reading (romaji)",
    kickerTypeB: "Pick the correct character",
    kickerTypeBKanji: "Pick the correct kanji",
    meaningPrefix: "Meaning:",
    inputPlaceholder: "type romaji...",
    btnCheckAnswer: "Check",
    btnNext: "Next →",
    btnSeeResult: "See Result",
    feedbackCorrect: "Correct!",
    feedbackWrong: "Not quite, don't give up!",
    answerPrefix: "Answer:",
    hintTitle: "Use hint",
    stageCompleteTitle: "Stage {n} Complete!",
    scoreLineLabel: "Correct answers:",
    lockNoteLocked: "Earn {need} more points in this category to unlock Stage {n}.",
    btnRetryStage: "Retry",
    btnGoHome: "Home",
    btnNextStage: "Next Stage →",
    autoSaveNote: "Your progress is saved automatically in this browser.",
    dailyBonusToast: "🔥 Daily bonus +{pts} points! {streak}-day streak",
    antiCopyToast: "Copy/inspect is disabled on this page.",
  },
};
